/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 283 283 1 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 283 283 2 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 283 283 3 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 283 283 4 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 283 283 5 256 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 448 448 1 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 448 448 2 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 448 448 3 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 448 448 4 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 448 448 5 256 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 1 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 2 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 3 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 5 256 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 16 40 633 633 1 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 16 40 633 633 2 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 16 40 633 633 3 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 16 40 633 633 4 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 16 40 633 633 5 256 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 1 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 2 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 3 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 5 256 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 64 156 300 300 1 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 64 156 300 300 2 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 64 156 300 300 3 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 64 156 300 300 4 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 64 156 300 300 5 256 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 1 256 1
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 256 1
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 256 2
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 256 8
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 256 16

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 1 64 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 2 64 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 3 64 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 64 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 5 64 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 1 128 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 2 128 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 3 128 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 128 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 5 128 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 1 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 2 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 3 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 256 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 5 256 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 1 512 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 2 512 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 3 512 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 512 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 5 512 4

/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 1 1024 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 2 1024 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 3 1024 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 4 1024 4
/cm/shared/apps/cuda12.8/visual-tools/12.8.0/bin/ncu --metrics sm__warps_active.avg.pct_of_peak_sustained_active,l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum,smsp__sass_average_branch_targets_threads_uniform.pct,launch__occupancy_per_shared_mem_size /home/jacksonna/code/finalproj/emisweep 32 78 633 633 5 1024 4

